"""Migracao Inicial

Revision ID: 1ef761028655
Revises: 
Create Date: 2026-07-29 12:46:39.693270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef761028655'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('rg', sa.String(length=30), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('nascimento', sa.DateTime(), nullable=True),
    sa.Column('profissao', sa.String(length=100), nullable=True),
    sa.Column('empresa', sa.String(length=100), nullable=True),
    sa.Column('renda', sa.String(length=50), nullable=True),
    sa.Column('estado_civil', sa.String(length=50), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('referencias', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('foto_path', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cpf'), 'clientes', ['cpf'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nome'), 'clientes', ['nome'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_login'), 'usuarios', ['login'], unique=True)
    op.create_table('emprestimos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('valor_emprestado', sa.Float(), nullable=False),
    sa.Column('valor_liberado', sa.Float(), nullable=False),
    sa.Column('taxa_juros', sa.Float(), nullable=False),
    sa.Column('tipo_juros', sa.String(length=50), nullable=False),
    sa.Column('quantidade_parcelas', sa.Integer(), nullable=False),
    sa.Column('periodicidade', sa.String(length=50), nullable=False),
    sa.Column('primeiro_vencimento', sa.DateTime(), nullable=False),
    sa.Column('garantia', sa.Text(), nullable=True),
    sa.Column('fiador', sa.String(length=150), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emprestimos_id'), 'emprestimos', ['id'], unique=False)
    op.create_table('parcelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emprestimo_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('capital', sa.Float(), nullable=False),
    sa.Column('juros', sa.Float(), nullable=False),
    sa.Column('multa', sa.Float(), nullable=True),
    sa.Column('desconto', sa.Float(), nullable=True),
    sa.Column('dias_atraso', sa.Integer(), nullable=True),
    sa.Column('valor_atualizado', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('operador_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['emprestimo_id'], ['emprestimos.id'], ),
    sa.ForeignKeyConstraint(['operador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcelas_id'), 'parcelas', ['id'], unique=False)
    op.create_table('renegociacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emprestimo_id', sa.Integer(), nullable=False),
    sa.Column('novo_valor', sa.Float(), nullable=False),
    sa.Column('nova_taxa', sa.Float(), nullable=False),
    sa.Column('novo_prazo', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('operador_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['emprestimo_id'], ['emprestimos.id'], ),
    sa.ForeignKeyConstraint(['operador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renegociacoes_id'), 'renegociacoes', ['id'], unique=False)
    op.create_table('recebimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=False),
    sa.Column('valor_pago', sa.Float(), nullable=False),
    sa.Column('tipo_pagamento', sa.String(length=50), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('operador_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recebimentos_id'), 'recebimentos', ['id'], unique=False)
    op.create_table('movimentacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('operador_id', sa.Integer(), nullable=True),
    sa.Column('recebimento_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['recebimento_id'], ['recebimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_id'), 'movimentacoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimentacoes_id'), table_name='movimentacoes')
    op.drop_table('movimentacoes')
    op.drop_index(op.f('ix_recebimentos_id'), table_name='recebimentos')
    op.drop_table('recebimentos')
    op.drop_index(op.f('ix_renegociacoes_id'), table_name='renegociacoes')
    op.drop_table('renegociacoes')
    op.drop_index(op.f('ix_parcelas_id'), table_name='parcelas')
    op.drop_table('parcelas')
    op.drop_index(op.f('ix_emprestimos_id'), table_name='emprestimos')
    op.drop_table('emprestimos')
    op.drop_index(op.f('ix_usuarios_login'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_clientes_nome'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cpf'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
