"""Add doc_identidade and doc_endereco to clientes

Revision ID: 89d4f47d1555
Revises: 1ef761028655
Create Date: 2026-08-09 12:30:15.126230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d4f47d1555'
down_revision: Union[str, Sequence[str], None] = '1ef761028655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('doc_identidade', sa.Text(), nullable=True))
    op.add_column('clientes', sa.Column('doc_endereco', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'doc_endereco')
    op.drop_column('clientes', 'doc_identidade')
    # ### end Alembic commands ###
