"""add_modalidade_to_emprestimo

Revision ID: c9acc972cbef
Revises: 89d4f47d1555
Create Date: 2026-09-17 10:46:49.306844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9acc972cbef'
down_revision: Union[str, Sequence[str], None] = '89d4f47d1555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emprestimos', sa.Column('modalidade', sa.String(length=50), nullable=False, server_default='MENSAL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emprestimos', 'modalidade')
    # ### end Alembic commands ###
